services:
  traefik:
    image: traefik:v3.0
    container_name: smetabot-traefik
    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --certificatesresolvers.le.acme.email=${LE_EMAIL}
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.le.acme.httpchallenge=true
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_letsencrypt:/letsencrypt
      - ./infra/traefik/dynamic:/etc/traefik/dynamic:ro
    restart: unless-stopped
    networks:
      - traefik

  db:
    image: postgres:15
    container_name: smetabot-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: ${TZ:-UTC}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./infra/migrations:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 6
    restart: unless-stopped
    ports:
    - "5432:5432"

  redis:
    image: redis:7.2-alpine
    container_name: smetabot-redis
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep -q PONG"]
      interval: 10s
      timeout: 3s
      retries: 6
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: smetabot-backend
    env_file:
      - .env
    environment:
      TZ: ${TZ:-UTC}
    volumes:
      - ./backend:/app
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "python - << 'PY'\nimport urllib.request,sys;sys.exit(0) if urllib.request.urlopen('http://localhost:8000/health', timeout=3).status==200 else sys.exit(1)\nPY"
        ]
      interval: 10s
      timeout: 3s
      retries: 6
      start_period: 15s
    restart: unless-stopped

  userbot:
    build:
      context: .
      dockerfile: userbot.Dockerfile
    container_name: smetabot-userbot
    env_file:
      - .env
    environment:
      TZ: ${TZ:-UTC}
      SESSIONS_DIR: /app/sessions
    volumes:
      - ./userbot:/app/userbot
      - userbot_sessions:/app/sessions
    expose:
      - "8001"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "python - << 'PY'\nimport urllib.request,sys;sys.exit(0) if urllib.request.urlopen('http://localhost:8001/health', timeout=3).status==200 else sys.exit(1)\nPY"
        ]
      interval: 15s
      timeout: 5s
      retries: 6
      start_period: 20s
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.userbot.rule=Host(`orbitsend.ru`)
      - traefik.http.routers.userbot.entrypoints=websecure
      - traefik.http.routers.userbot.tls=true
      - traefik.http.routers.userbot.tls.certresolver=le
      - traefik.http.services.userbot.loadbalancer.server.port=8001
      - traefik.http.middlewares.userbot-compress.compress=true
      - traefik.http.routers.userbot.middlewares=userbot-compress

  bot:
    build:
      context: .
      dockerfile: bot.Dockerfile
    container_name: smetabot-bot
    env_file:
      - .env
    environment:
      TZ: ${TZ:-UTC}
      USERBOT_URL: http://userbot:8001
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
    volumes:
      - ./bot:/app/bot
    depends_on:
      redis:
        condition: service_healthy
      userbot:
        condition: service_healthy
      backend:
        condition: service_started
    restart: unless-stopped
    networks:
      - default
      - traefik

  worker_pdf:
    build:
      context: .
      dockerfile: worker.Dockerfile
    container_name: smetabot-worker-pdf
    env_file:
      - .env
    environment:
      TZ: ${TZ:-UTC}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
      METRICS_PORT: ${WORKER_PDF_METRICS_PORT:-9464}
      CELERY_CONCURRENCY: ${WORKER_PDF_CONCURRENCY:-3}
      CELERY_QUEUES: ${WORKER_PDF_QUEUES:-pdf,default}
    volumes:
      - ./worker:/app/worker
    depends_on:
      redis:
        condition: service_healthy
      backend:
        condition: service_started
    expose:
      - "${WORKER_PDF_METRICS_PORT:-9464}"
    restart: unless-stopped

  worker_publish:
    build:
      context: .
      dockerfile: worker.Dockerfile
    container_name: smetabot-worker-publish
    env_file:
      - .env
    environment:
      TZ: ${TZ:-UTC}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
      METRICS_PORT: ${WORKER_PUBLISH_METRICS_PORT:-9465}
      CELERY_CONCURRENCY: ${WORKER_PUBLISH_CONCURRENCY:-2}
      CELERY_QUEUES: ${WORKER_PUBLISH_QUEUES:-publish}
    volumes:
      - ./worker:/app/worker
    depends_on:
      redis:
        condition: service_healthy
      backend:
        condition: service_started
    expose:
      - "${WORKER_PUBLISH_METRICS_PORT:-9465}"
    restart: unless-stopped

  worker_office:
    build:
      context: .
      dockerfile: worker.Dockerfile
    container_name: smetabot-worker-office
    env_file:
      - .env
    environment:
      TZ: ${TZ:-UTC}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
      METRICS_PORT: ${WORKER_OFFICE_METRICS_PORT:-9466}
      CELERY_CONCURRENCY: ${WORKER_OFFICE_CONCURRENCY:-1}
      CELERY_QUEUES: ${WORKER_OFFICE_QUEUES:-office}
    volumes:
      - ./worker:/app/worker
    depends_on:
      redis:
        condition: service_healthy
      backend:
        condition: service_started
    expose:
      - "${WORKER_OFFICE_METRICS_PORT:-9466}"
    restart: unless-stopped

  worker_preview:
    build:
      context: .
      dockerfile: worker.Dockerfile
    container_name: smetabot-worker-preview
    env_file:
      - .env
    environment:
      TZ: ${TZ:-UTC}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
      METRICS_PORT: ${WORKER_PREVIEW_METRICS_PORT:-9467}
      CELERY_CONCURRENCY: ${WORKER_PREVIEW_CONCURRENCY:-2}
      CELERY_QUEUES: ${WORKER_PREVIEW_QUEUES:-preview}
    volumes:
      - ./worker:/app/worker
    depends_on:
      redis:
        condition: service_healthy
      backend:
        condition: service_started
    expose:
      - "${WORKER_PREVIEW_METRICS_PORT:-9467}"
    restart: unless-stopped

  flower:
    image: mher/flower:2.0.1
    container_name: smetabot-flower
    command:
      - "celery"
      - "--broker=${REDIS_URL:-redis://redis:6379/0}"
      - "flower"
      - "--port=5555"
      - "--persistent=True"
    environment:
      TZ: ${TZ:-UTC}
      FLOWER_BASIC_AUTH: ${FLOWER_BASIC_AUTH:-}
      CELERY_BROKER_URL: ${REDIS_URL:-redis://redis:6379/0}
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "${FLOWER_PORT:-5555}:5555"
    restart: unless-stopped

volumes:
  pgdata: {}
  userbot_sessions: {}
  traefik_letsencrypt: {}

networks:
  traefik:
    name: traefik
