services:
  backend:
    env_file:
      - .env.dev
  userbot:
    env_file:
      - .env.dev
    ports:
      - "8001:8001"
  bot:
    env_file:
      - .env.dev
  worker:
    env_file:
      - .env.dev
