services:
  backend:
    env_file:
      - .env.dev
  userbot:
    env_file:
      - .env.dev
    ports:
      - "8001:8001"
  bot:
    env_file:
      - .env.dev
  worker_pdf:
    env_file:
      - .env.dev
  worker_publish:
    env_file:
      - .env.dev
  worker_office:
    env_file:
      - .env.dev
  worker_preview:
    env_file:
      - .env.dev
